//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 08:37:51 PM EDT 
//


package org.restsql.core.sqlresource;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.restsql.core.sqlresource package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SqlResource_QNAME = new QName("http://restsql.org/schema", "sqlResource");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.restsql.core.sqlresource
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentationDescription }
     * 
     */
    public DocumentationDescription createDocumentationDescription() {
        return new DocumentationDescription();
    }

    /**
     * Create an instance of {@link DocumentationExamples }
     * 
     */
    public DocumentationExamples createDocumentationExamples() {
        return new DocumentationExamples();
    }

    /**
     * Create an instance of {@link DocumentationColumns }
     * 
     */
    public DocumentationColumns createDocumentationColumns() {
        return new DocumentationColumns();
    }

    /**
     * Create an instance of {@link HttpConfig }
     * 
     */
    public HttpConfig createHttpConfig() {
        return new HttpConfig();
    }

    /**
     * Create an instance of {@link HttpResponse }
     * 
     */
    public HttpResponse createHttpResponse() {
        return new HttpResponse();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link DocumentationColumn }
     * 
     */
    public DocumentationColumn createDocumentationColumn() {
        return new DocumentationColumn();
    }

    /**
     * Create an instance of {@link DocumentationResource }
     * 
     */
    public DocumentationResource createDocumentationResource() {
        return new DocumentationResource();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link ValidatedAttribute }
     * 
     */
    public ValidatedAttribute createValidatedAttribute() {
        return new ValidatedAttribute();
    }

    /**
     * Create an instance of {@link DocumentationExample }
     * 
     */
    public DocumentationExample createDocumentationExample() {
        return new DocumentationExample();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link DocumentationRequest }
     * 
     */
    public DocumentationRequest createDocumentationRequest() {
        return new DocumentationRequest();
    }

    /**
     * Create an instance of {@link DocumentationHeader }
     * 
     */
    public DocumentationHeader createDocumentationHeader() {
        return new DocumentationHeader();
    }

    /**
     * Create an instance of {@link SqlResourceDefinition }
     * 
     */
    public SqlResourceDefinition createSqlResourceDefinition() {
        return new SqlResourceDefinition();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link DocumentationResponse }
     * 
     */
    public DocumentationResponse createDocumentationResponse() {
        return new DocumentationResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SqlResourceDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://restsql.org/schema", name = "sqlResource")
    public JAXBElement<SqlResourceDefinition> createSqlResource(SqlResourceDefinition value) {
        return new JAXBElement<SqlResourceDefinition>(_SqlResource_QNAME, SqlResourceDefinition.class, null, value);
    }

}
