//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.12 at 06:05:14 PM EDT 
//


package org.restsql.core.sqlresource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SqlResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SqlResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="query" type="{http://restsql.org/schema}Query"/>
 *         &lt;element name="validatedAttribute" type="{http://restsql.org/schema}ValidatedAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultDatabase" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentExt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="child" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="childExt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="join" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SqlResource", propOrder = {
    "query",
    "validatedAttribute"
})
public class SqlResourceDefinition {

    @XmlElement(required = true)
    protected Query query;
    protected List<ValidatedAttribute> validatedAttribute;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "defaultDatabase", required = true)
    protected String defaultDatabase;
    @XmlAttribute(name = "parent", required = true)
    protected String parent;
    @XmlAttribute(name = "parentExt")
    protected String parentExt;
    @XmlAttribute(name = "child")
    protected String child;
    @XmlAttribute(name = "childExt")
    protected String childExt;
    @XmlAttribute(name = "join")
    protected String join;

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link Query }
     *     
     */
    public Query getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link Query }
     *     
     */
    public void setQuery(Query value) {
        this.query = value;
    }

    /**
     * Gets the value of the validatedAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validatedAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidatedAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidatedAttribute }
     * 
     * 
     */
    public List<ValidatedAttribute> getValidatedAttribute() {
        if (validatedAttribute == null) {
            validatedAttribute = new ArrayList<ValidatedAttribute>();
        }
        return this.validatedAttribute;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the defaultDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDatabase() {
        return defaultDatabase;
    }

    /**
     * Sets the value of the defaultDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDatabase(String value) {
        this.defaultDatabase = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the parentExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentExt() {
        return parentExt;
    }

    /**
     * Sets the value of the parentExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentExt(String value) {
        this.parentExt = value;
    }

    /**
     * Gets the value of the child property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChild(String value) {
        this.child = value;
    }

    /**
     * Gets the value of the childExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildExt() {
        return childExt;
    }

    /**
     * Sets the value of the childExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildExt(String value) {
        this.childExt = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoin(String value) {
        this.join = value;
    }

}
